import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Sidebar from "../components/Sidebar";
import Feed from "../components/Feed";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Twitter-clone</title>
        <meta name="description"
              content="Generated by create next app"/>
        <link rel="icon"
              href="/favicon.ico"/>
      </Head>

      <main className="bg-white min-h-screen flex max-w-[1500px] mx-auto">
        <Sidebar/>
        <Feed/>
        {/* Widgets */}

        {/*  */}
      </main>
    </div>
  )
}
